# This is a boilerplate parameters config generated for pipeline 'generate_adversarial_examples'
# using Kedro 0.18.13.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.13/configuration/parameters.html

Fast_Signed_attack:
  eps: [0.01,0.05,0.1,0.5,1]


Adversarial_Attacks:
  FSGM:
    module: art.attacks.evasion
    class: FastGradientMethod
    kwargs:
      # eps_step: 0.001
      eps: 0.01
      norm: inf
      minimal: False
      batch_size: 128
      targeted: False #This means that we do not care for specific class
  DeepFool:
    module: art.attacks.evasion
    class: DeepFool 
    kwargs:
      max_iter: 10
      epsilon: 0.01
      nb_grads: 10
      batch_size: 256
  CarliniL2:
    module: art.attacks.evasion
    class: CarliniL2Method 
    kwargs:
      confidence: 1
      targeted: False
      learning_rate: 0.01
      binary_search_steps: 5
      max_iter: 10
      initial_const: 0.01
      max_halving: 5
      max_doubling: 5
      batch_size: 256
      verbose: True

  PGD:
    module: art.attacks.evasion
    class: ProjectedGradientDescent 
    kwargs:
      eps: 0.01
      eps_step: 0.005
      max_iter: 10
      batch_size: 256
      num_random_init: 1

Attacks_to_use:
  # attacks: ["DeepFool", "CarliniL2","FSGM","PGD"]
  attacks: ["FSGM"] 
